
### Objective: Predict whether or not LeBron James will break the all time 
### NBA career point record and if so, when he will break the record

library(rvest)
library(dplyr)
library(ggplot2)
library(data.table)

# Create tibbles for each player
#########################################################################
kareem <- tibble(
  player_name = 'Kareem Abdul-Jabbar',
  player_id = 'abdulka01',
  initial = 'a',
  year = 1970:1989)

malone <- tibble(
  player_name = 'Karl Malone',
  player_id = 'malonka01',
  initial = 'm',
  year = 1986:2004)

lebron <- tibble(
  player_name = 'LeBron James',
  player_id = 'jamesle01',
  initial = 'j',
  year = 2004:2020)

kobe <- tibble(
  player_name = 'Kobe Bryant',
  player_id = 'bryanko01',
  initial = 'b',
  year = 1997:2016)

jordan <- tibble(
  player_name = 'Michael Jordan',
  player_id = 'jordami01',
  initial = 'j',
  year = 1985:2003)

# Create df & URLs of players to be scraped
#########################################################################

players = bind_rows(kareem, malone, lebron, kobe, jordan)

urls <- sprintf("https://www.basketball-reference.com/players/%s/%s/gamelog/%s", 
                players$initial, players$player_id, players$year)

# Stack player data in data frame
#########################################################################
output <- data_frame()

purrr::map_df(urls, ~{
  .x %>%  
    read_html() %>%
    html_nodes("#pgl_basic") %>% 
    html_table() -> tmp
    
  if(length(tmp)) {
    tmp <- tmp[[1]]
    setNames(tmp, paste0('col', seq_along(tmp))) %>%
      mutate(across(.fns = as.character)) 
  }
  else NULL
}, .id = 'playername') %>% 
  mutate(playername = players$player_name[as.numeric(playername)]) -> output




# Clean out header values generated by scraping multiple pages
# Only keep columns of interest
# Fix games with no points or character values
clean <- output %>% 
  subset(col3 != "Date") %>%
  rename(date = col3, pts = col20) %>%
  select(playername,date,pts) %>% 
  mutate(pts = as.numeric(pts)) %>% 
  mutate(game_pts=ifelse(is.na(pts), 0,as.numeric(pts)))

# Add cumulative career points
career_pts <- data.table(clean, key = "playername")
career_pts[, csum := cumsum(game_pts), by = key(career_pts)]

# Convert game date to date format
career_pts$g_date = as.Date(career_pts$date)

# Create a sequence to represent the game number of each players career
career_pts$game_num <- with(career_pts, ave(playername, playername, FUN = seq_along))

# Create plot
ggplot(data=career_pts, aes(x=factor(game_num), y=csum, color=playername)) +
  geom_point(size=1, color='red') +
  # scale_x_continuous(breaks=seq(0,1400,100)) +
  theme_minimal() +
  labs(x = "Game #", y = "Career Points")
  # shadow_mark()


